apiVersion: v1
kind: Service
metadata:
  name: barcode-reader-kubernetes-service
  namespace: supermarket
spec:
  type: LoadBalancer
  ports:
    - port: 99
      targetPort: 8099
  selector:
    app: barcode-reader
