apiVersion: v1
kind: Service
metadata:
  name: e-shopping-kubernetes-service
  namespace: supermarket
spec:
  type: LoadBalancer
  ports:
    - port: 82
      targetPort: 8082
  selector:
    app: e-shopping