apiVersion: v1
kind: Service
metadata:
  name: supermarket-api-gateway-kubernetes-service
  namespace: supermarket
spec:
  type: LoadBalancer
  ports:
    - port: 96
      targetPort: 8096
  selector:
    app: supermarket-api-gateway