apiVersion: v1
kind: Service
metadata:
  name: customer-kubernetes-service
  namespace: supermarket
spec:
  type: ClusterIP
  ports:
    - port: 98
      targetPort: 8098
  selector:
    app: customer-microservice
