apiVersion: v1
kind: Service
metadata:
  name: payment-kubernetes-service
  namespace: supermarket
spec:
  type: LoadBalancer
  ports:
    - port: 83
      targetPort: 8083
  selector:
    app: payment