apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: supermarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: supermarket/payment
          imagePullPolicy: Never
          ports:
            - containerPort: 8083