apiVersion: v1
kind: Service
metadata:
  name: reservation-kubernetes-service
  namespace: supermarket
spec:
  type: ClusterIP
  ports:
    - port: 81
      targetPort: 8081
  selector:
    app: reservation