apiVersion: v1
kind: Service
metadata:
  name: stock-kubernetes-service
  namespace: supermarket
spec:
  type: LoadBalancer
  ports:
    - port: 91
      targetPort: 8091
  selector:
    app: stock-microservice
