server:
  port: 8096
---
spring:
  application.name: supermarket

  security:
    enable-csrf: false
    oauth2:
      client:
        registration:
          google:
            client-id: 586330299500-g48p3cj9bvtjn32f1d3q4797gl4jo0kc.apps.googleusercontent.com
            client-secret: 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
  cloud:
    gateway:
#      default-filters:
#        - name: AuthenticationConfig
      routes:
#        - id: authentication
#          uri: http://localhost:8097/
#          predicates:
#            - Path=/authentication-microservice/**
        - id: customer-microservice
          uri: http://localhost:8098/
          predicates:
            - Path=/customer-microservice/**
        - id: barcode-reader
          uri: http://localhost:8099/
          predicates:
            - Path=/barcode-reader/**
#  main:
#    allow-bean-definition-overriding: true
#    web-application-type: reactive



