apiVersion: v1
kind: Service
metadata:
  name: authentication-kubernetes-service
  namespace: supermarket
spec:
  type: LoadBalancer
  ports:
    - port: 97
      targetPort: 8097
  selector:
    app: authentication-microservice
